# position controllers ---------------------------------------
  back_lbz_position_controller:
    type: position_controllers/JointPositionController
    joint: back_lbz
    pid: {p: 10.0, i: 0.0, d: 0.0}

  back_mby_position_controller:
    type: position_controllers/JointPositionController
    joint: back_mby
    pid: {p: 10.0, i: 0.0, d: 0.0}

  back_ubx_position_controller:
    type: position_controllers/JointPositionController
    joint: back_ubx
    pid: {p: 10.0, i: 0.0, d: 0.0}

  neck_ay_position_controller:
    type: position_controllers/JointPositionController
    joint: neck_ay
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_leg_uhz_position_controller:
    type: position_controllers/JointPositionController
    joint: l_leg_uhz
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_leg_mhx_position_controller:
    type: position_controllers/JointPositionController
    joint: l_leg_mhx
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_leg_lhy_position_controller:
    type: position_controllers/JointPositionController
    joint: l_leg_lhy
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_leg_kny_position_controller:
    type: position_controllers/JointPositionController
    joint: l_leg_kny
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  l_leg_uay_position_controller:
    type: position_controllers/JointPositionController
    joint: l_leg_uay
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  l_leg_lax_position_controller:
    type: position_controllers/JointPositionController
    joint: l_leg_lax
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  r_leg_uhz_position_controller:
    type: position_controllers/JointPositionController
    joint: r_leg_uhz
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_leg_mhx_position_controller:
    type: position_controllers/JointPositionController
    joint: r_leg_mhx
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_leg_lhy_position_controller:
    type: position_controllers/JointPositionController
    joint: r_leg_lhy
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_leg_kny_position_controller:
    type: position_controllers/JointPositionController
    joint: r_leg_kny
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  r_leg_uay_position_controller:
    type: position_controllers/JointPositionController
    joint: r_leg_uay
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  r_leg_lax_position_controller:
    type: position_controllers/JointPositionController
    joint: r_leg_lax
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  l_arm_usy_position_controller:
    type: position_controllers/JointPositionController
    joint: l_arm_usy
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_arm_shx_position_controller:
    type: position_controllers/JointPositionController
    joint: l_arm_shx
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_arm_ely_position_controller:
    type: position_controllers/JointPositionController
    joint: l_arm_ely
    pid: {p: 10.0, i: 0.0, d: 0.0}

  l_arm_elx_position_controller:
    type: position_controllers/JointPositionController
    joint: l_arm_elx
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  l_arm_uwy_position_controller:
    type: position_controllers/JointPositionController
    joint: l_arm_uwy
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  l_arm_mwx_position_controller:
    type: position_controllers/JointPositionController
    joint: l_arm_mwx
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  r_arm_usy_position_controller:
    type: position_controllers/JointPositionController
    joint: r_arm_usy
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_arm_shx_position_controller:
    type: position_controllers/JointPositionController
    joint: r_arm_shx
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_arm_ely_position_controller:
    type: position_controllers/JointPositionController
    joint: r_arm_ely
    pid: {p: 10.0, i: 0.0, d: 0.0}

  r_arm_elx_position_controller:
    type: position_controllers/JointPositionController
    joint: r_arm_elx
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  r_arm_uwy_position_controller:
    type: position_controllers/JointPositionController
    joint: r_arm_uwy
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  r_arm_mwx_position_controller:
    type: position_controllers/JointPositionController
    joint: r_arm_mwx
    pid: {p: 10.0, i: 0.0, d: 0.0}    