# trajectory controllers ---------------------------------------
atlas_control:
  left_arm_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - l_arm_shy
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_wry
      - l_arm_wrx

  right_arm_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - r_arm_shy
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
      
  torso_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - back_bkz
      - back_bky
      - back_bkx