# trajectory controllers ---------------------------------------
atlas_control:
  left_arm_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - l_arm_shy
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_wry
      - l_arm_wrx

  right_arm_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - r_arm_shy
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
      
  torso_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - back_bkz
      - back_bky
      - back_bkx
      
  left_leg_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - l_leg_hpz
      - l_leg_hpx
      - l_leg_hpy
      - l_leg_kny
      - l_leg_aky
      - l_leg_akx
      
  right_leg_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - r_leg_hpz
      - r_leg_hpx
      - r_leg_hpy
      - r_leg_kny
      - r_leg_aky
      - r_leg_akx
      
  neck_position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - neck_ry