sensors:
 - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
   image_topic: /kinect/depth/2hz_playback_depth
   queue_size: 5
   near_clipping_plane_distance: 0.15
   far_clipping_plane_distance: 1.5
   skip_vertical_pixels: 3
   skip_horizontal_pixels: 3
   shadow_threshold: 0.2
   padding_scale: 4.0
   padding_offset: 0.03
   filtered_cloud_topic: filtered_depth_cloud
